### ISSUE TITLE
Mobile Sign-Up No Longer Relevant

### ISSUE THREAD

**Issue by alihen** [gpolak/GPUberView#2]
Hi there,

While integrating this control into my app, I noticed that the directing the user to m.uber.com with user parameters no longer works and instead jumps to the app store. While investigating I found that Uber had made this change a few months ago, mentioned below:

> Within the next month, we will begin redirecting all desktop users from m.uber.com/sign-up to get.uber.com, while mobile users will be directed to the appropriate Uber app store page. You will not need to change your current m.uber signup link, but please make sure that you are not wrapping m.uber in a webview. In addition, rider promos will no longer be applied directly to users that come from developer apps.

Would it be safe to say that the user parameter function should be deprecated as it doesn't serve a purpose anymore?

**Comment by gpolak** [comment]
Thanks @alihen. I've deprecated the user params in the new version (1.1.0). Nice catch!
