### ISSUE TITLE
Changes to [UIApplication sharedApplication] canOpenURL in iOS 9

### ISSUE THREAD

**Issue by alihen** [gpolak/GPUberView#3]
I jumped back into integrating this into an app today and noticed that `canOpenURL` no longer returns YES when an app is installed.

Apparently this is a change in iOS 9, where the scheme needs to be whitelisted in `Info.plist`.

Would it be possible be add this to the README?
Will submit PR if I've got some time :blush: 

Source: http://awkwardhare.com/post/121196006730/quick-take-on-ios-9-url-scheme-changes

EDIT: Looks like `canOpenURL` should just be `openURL` to solve this issue.

**Comment by gpolak** [comment]
Thanks for the heads-up @alihen . I'll add this later this week.

**Comment by gpolak** [comment]
Updated for iOS 9. Thanks again @alihen 

https://github.com/gpolak/GPUberView/releases/tag/1.1.1
