### ISSUE TITLE
Need to upgrade the AFNetworking dependency

### ISSUE THREAD

**Issue by akashgupta88** [gpolak/GPUberView#4]
AFNetworking has been upgraded to 3.0 (where AFHTTPRequestOperationManager has been deprecated).

The AFNetworking dependency needs to upgraded to support the same. This will prevent errors with upgrading AFNetworking for use within our own apps as well.

**Comment by gpolak** [comment]
Good call @akashgupta88. I think I'll just remove the AFNetworking dependency altogether - it's a bit of an overkill for the couple of calls I'm making anyway.

**Comment by gpolak** [comment]
Removed AFNetworking: https://github.com/gpolak/GPUberView/commit/e36fb14a1c0b2ec75c55c4cc3d917d3c66ab9a7a

**Comment by akashgupta88** [comment]
Great!

I tried updating the pod using pod update, but it still causes conflicts:

```
- `INTULocationManager` required by `Podfile`
- `INTULocationManager (= 4.1.1)` required by `Podfile.lock`
- `INTULocationManager (~> 2.0)` required by `GPUberView (1.0)`
- `AFNetworking (~> 3.0.0)` required by `Podfile`
- `AFNetworking (~> 2.5)` required by `GPUberView (0.1)`
```

I tried removing the pod, cleaning the cache and installing it again but to no avail.

**Comment by gpolak** [comment]
Hi Akash,

I haven't updated the pod yet, just the source. I'll bump the version this weekend.

**Comment by gpolak** [comment]
Pods updated. AFNetworking removed in 1.1.4
