### ISSUE TITLE
INTULocationManager upgrade

### ISSUE THREAD

**Issue by akashgupta88** [gpolak/GPUberView#5]
Sorry for sounding like a broken record, but will it be possible to update the INTULocationManager dependency to 4.1.1 as well? I'm using INTULocationManager in my application as well, and an stuck with GPUberView version 0.5 when using pod install.

Though the AFNetworking dependency issue was solved, upgrading GPUberView now causes the following error:

```
$ pod update GPUberView

Updating local specs repositories
Analyzing dependencies
[!] Unable to satisfy the following requirements:

- `INTULocationManager` required by `Podfile`
- `INTULocationManager (= 4.1.1)` required by `Podfile.lock`
- `INTULocationManager (~> 2.0)` required by `GPUberView (1.1.0)` 
```

**Comment by gpolak** [comment]
Done in GPUberView 1.1.5.

**Comment by akashgupta88** [comment]
That was quick... Thanks!
